# Generated by Django 5.1.4 on 2025-01-03 22:42

import app.amal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyahGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=app.amal.models.current_timestamp, editable=False)),
                ('updated_at', models.FloatField(default=app.amal.models.current_timestamp, editable=False)),
                ('title', models.TextField(max_length=100)),
                ('subtitle', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=app.amal.models.current_timestamp, editable=False)),
                ('updated_at', models.FloatField(default=app.amal.models.current_timestamp, editable=False)),
                ('position', models.IntegerField(default=0)),
                ('title', models.TextField(max_length=500)),
                ('arabic', models.TextField(blank=True, null=True)),
                ('indopak', models.TextField(blank=True, null=True)),
                ('bangla', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(max_length=200)),
                ('audiopath', models.TextField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amal.ayahgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
