# Generated by Django 5.1.4 on 2025-01-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amal', '0002_ayah_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayah',
            name='ref',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
