# Generated by Django 5.1.4 on 2025-01-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amal', '0003_alter_ayah_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('data_version', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('schema_version', 'data_version')},
            },
        ),
    ]
